FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /usr/local/app/

RUN apt-get update \
    && apt-get install -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget -qO- https://github.com/block-core/angor/releases/download/#{VERSIONTAG}#/Angor-#{VERSION}#-linux-x64.tar.gz | tar xvz

EXPOSE 5500
ENTRYPOINT ["dotnet", "Angor.Server.dll"]