// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Angor.Contexts.Data.Migrations
{
    [DbContext(typeof(AngorDbContext))]
    partial class AngorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Angor.Contexts.Data.Entities.NostrEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Kind");

                    b.HasIndex("PubKey");

                    b.ToTable("NostrEvents");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.NostrUser", b =>
                {
                    b.Property<string>("PubKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("About")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Banner")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nip05")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PubKey");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Nip05");

                    b.ToTable("NostrUsers");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FundingEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FundingStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadInvestorsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NostrPubKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("PenaltyDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectInfoEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectReceiveAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("FundingEndDate");

                    b.HasIndex("FundingStartDate");

                    b.HasIndex("NostrPubKey");

                    b.HasIndex("ProjectInfoEventId");

                    b.HasIndex("ProjectReceiveAddress");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.ProjectSecretHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "SecretHash")
                        .IsUnique();

                    b.ToTable("ProjectSecretHash");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.ProjectStage", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("StageIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountToRelease")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "StageIndex");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("ProjectStage");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.NostrEvent", b =>
                {
                    b.HasOne("Angor.Contexts.Data.Entities.NostrUser", "User")
                        .WithMany("Events")
                        .HasForeignKey("PubKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.Project", b =>
                {
                    b.HasOne("Angor.Contexts.Data.Entities.NostrUser", "NostrUser")
                        .WithMany()
                        .HasForeignKey("NostrPubKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Angor.Contexts.Data.Entities.NostrEvent", "NostrEvent")
                        .WithMany()
                        .HasForeignKey("ProjectInfoEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NostrEvent");

                    b.Navigation("NostrUser");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.ProjectSecretHash", b =>
                {
                    b.HasOne("Angor.Contexts.Data.Entities.Project", "Project")
                        .WithMany("SecretHashes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.ProjectStage", b =>
                {
                    b.HasOne("Angor.Contexts.Data.Entities.Project", "Project")
                        .WithMany("Stages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.NostrUser", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Angor.Contexts.Data.Entities.Project", b =>
                {
                    b.Navigation("SecretHashes");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
