FROM mcr.microsoft.com/dotnet/sdk:9.0.301

# Install OpenSSL for cryptographic operations
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

# Ensure WASM tools are installed
RUN dotnet workload install wasm-tools

# Set default working directory
WORKDIR /source
